variables:
  MAVEN_CLI_OPTS: "clean"
  EXECUTABLE_POM_FILE_PATH: "Group5"

stages:
    - build
    
build:
  stage: build
  image: maven:3.6.3-jdk-11
  before_script:
    - cd $EXECUTABLE_POM_FILE_PATH
  script:
    - mvn compile
  tags:
    - dalfcs_gitlab_docker_ci