image: maven:latest

variables:
  MAVEN_CLI_OPTS: "clean"
  EXECUTABLE_POM_FILE_PATH: "Group 5"

stages:
    - build
    - test
    - deployTest
    
build:
  stage: build
  image: maven:latest
  before_script:
    - cd $EXECUTABLE_POM_FILE_PATH
  script:
    - mvn $MAVEN_CLI_OPTS compile
  tags:
    - grad
  only:
    - development

test:
  stage: test
  image: maven:latest
  before_script:
    - cd $EXECUTABLE_POM_FILE_PATH
  script:
    - mvn verify
  artifacts:
    when: always
    paths: 
        - $EXECUTABLE_POM_FILE_PATH/target/surefire-reports/TEST-*.xml
    reports:
      junit:
        - $EXECUTABLE_POM_FILE_PATH/target/surefire-reports/TEST-*.xml
  tags:
    - grad
  only:
    - development
    
deployeTest:
  stage: deployTest
  image: ruby:latest
  before_script:
    - cd $EXECUTABLE_POM_FILE_PATH
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_NAME_TEST --api-key=$HEROKU_API_KEY_TEST
  tags:
    - grad
  only:
    - development