variables:
  MAVEN_CLI_OPTS: "clean"
  EXECUTABLE_POM_FILE_PATH: "Group5"

stages:
    - build
    - test
    - deployTest
    
build:
  stage: build
  image: maven:3.6.3-jdk-11
  before_script:
    - cd $EXECUTABLE_POM_FILE_PATH
  script:
    - mvn install
  tags:
    - dalfcs_gitlab_docker_ci

test:
  stage: test
  image: maven:3.6.3-jdk-11
  before_script:
    - cd $EXECUTABLE_POM_FILE_PATH
  script:
    - mvn test
  artifacts:
    when: always
    paths: 
        - $EXECUTABLE_POM_FILE_PATH/target/surefire-reports/TEST-*.xml
    reports:
      junit:
        - $EXECUTABLE_POM_FILE_PATH/target/surefire-reports/TEST-*.xml
  tags:
   - dalfcs_gitlab_docker_ci
    
deployeTest:
  stage: deployTest
  image: ruby:latest
  script:
    - cd $EXECUTABLE_POM_FILE_PATH
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_NAME_TEST --api-key=$HEROKU_API_KEY_TEST
  environment:
    name: staging
    url: $HEROKU_TEST_URL
  tags:
    - dalfcs_gitlab_docker_ci
  only:
    - development