variables:
  MAVEN_CLI_OPTS: "clean"
  EXECUTABLE_POM_FILE_PATH: "Group5"

stages:
    - build
    
build:
  stage: build
  image: maven:3.3.9-jdk-8
  before_script:
    - cd $EXECUTABLE_POM_FILE_PATH
  script:
    - mvn clean compile
  tags:
    - dalfcs_docker_kvm